name: Scraping Automatisation

on:
  schedule:
    # Run every day at 00:00 UTC
    - cron: '0 0 1 */3 *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4 pandas

    - name: Run scraping script
      env: 
          USERNAME: ${{ secrets.USERNAME }} 
          PASSWORD: ${{ secrets.PASSWORD }}
      run: python ScrapingAutomatisation.py
      
    - name: Save output as CSV
      run: python -c "import pandas as pd; df = pd.read_pickle('games.pkl'); df.to_csv('games.csv', index=False)"
    
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add games.csv
        git commit -m 'Update games.csv'
        git push
